# # nginx-ingress-controller.yaml
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: ingress-nginx
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: ingress-nginx
#   namespace: ingress-nginx
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: ingress-nginx-controller
#   namespace: ingress-nginx
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ingress-nginx-controller
#   namespace: ingress-nginx
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: ingress-nginx
#   template:
#     metadata:
#       labels:
#         app: ingress-nginx
#     spec:
#       serviceAccountName: ingress-nginx
#       containers:
#         - name: controller
#           image: registry.k8s.io/ingress-nginx/controller:v1.8.2
#           args:
#             - /nginx-ingress-controller
#             - --publish-service=ingress-nginx/ingress-nginx-controller
#           ports:
#             - name: http
#               containerPort: 80
#             - name: https
#               containerPort: 443
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ingress-nginx-controller
#   namespace: ingress-nginx
# spec:
#   type: NodePort
#   ports:
#     - port: 80
#       targetPort: 80
#       protocol: TCP
#       name: http
#     - port: 443
#       targetPort: 443
#       protocol: TCP
#       name: https
#   selector:
#     app: ingress-nginx
