apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx  # This matches the label in your pod definition
  ports:
    - port: 80        # Port the service listens on
      targetPort: 80  # Port to forward to in the pod (matches containerPort)
      protocol: TCP
