apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-test
  namespace: argo-cd-test
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: argo-cd-test/default.yaml
    targetRevision: HEAD
    repoURL: https://github.com/ngahoangvan/k8s-learning-note
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
